# Site settings
title: Bench随便写点东西的地方
SEOTitle: Bench的博客
header-img: img/post-bg-desk.jpg
email: zhenzhendeng2012@gmail.com
description: "Keep hands dirty, keep coding."
keyword: "Python, Data, ML"
url: "http://dengzhenzhen.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/dengzhenzhen/dengzhenzhen.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Scan here to wechat me "
sidebar-avatar: /img/715e7edc65904110b0bb9b52e24272b1-560x560.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     2995800843 
zhihu_username:     bench
github_username:    dengzhenzhen
#facebook_username:  
#jianshu_username:   
#twitter_username:   




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
#Disqus: https://disqus.com/
#disqus_username: dengzhenzhen

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 35df3c9e9ebf8d34d04b                            #生成的clientID
  clientSecret: a64199bf002427c3896774554d1749f6c9367a13    #生成的clientSecret
  repo: dengzhenzhen.github.io    #仓库名称
  owner: dengzhenzhen    #github用户名
  admin: dengzhenzhen
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-123015399-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto

math:
  enable: true
  # Default(true) will load mathjax/katex script on demand
  # That is it only render those page who has 'mathjax: true' in Front Matter.
  # If you set it to false, it will load mathjax/katex srcipt EVERY PAGE.
  per_page: false
  engine: mathjax



# Featured Tags
featured-tags: true                    # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
